"""Issue 001 editorial expansion postprocessor."""
from pathlib import Path

DATA = {
"card_01": ["A Korean community thread registers an expectation gap inside global K-pop fandom; it is evidence of tension, not a verdict on either side.", "K-pop now travels through translation accounts, short-form clips, touring, and platform-native communities. Shared enthusiasm puts different expectations about criticism, identity, and belonging into one conversation.", "TheQoo Square is a Korean community board where posts can reach high visibility. A visible thread shows what some participants discussed; it does not measure Korean public opinion or all K-pop fans.", "The useful question is whether global spaces can criticize Korea without flattening Korean people—and whether Korean fans can describe hurt without turning individual comments into a story about every overseas fan.", "The strongest signal is a loss of trust. That feeling matters even when one thread cannot establish its scale.", "Whether the language appears across separate communities|How translation accounts frame Korean criticism|Whether organizers create clearer cross-cultural norms", "SOURCE THREAD → COMMENT MOOD → EXPECTATION GAP", "Do not generalize Korean fans, overseas fans, or national opinion."],
"card_02": ["Fans are treating “Work” as an underused promotional opportunity and publicly doing work an A&R or marketing team normally owns.", "In the Shorts and challenge era, a release can develop a second promotional life. Clips, choreography, and fan edits make listeners evaluate how quickly an agency responds to visible momentum.", "TheQoo post discusses “Work,” “Zap,” Hot-board attention, and a performance-video count observed by the poster. Those are community cues, not audited demand or proof of an agency decision.", "Fandom is acting like a distributed focus group: identifying the hook, comparing tracks, proposing short-form tactics, and keeping an alternative visible.", "The frustration is about responsiveness. The story is free A&R—not a definitive finding that the agency failed.", "New official clips or stages for Work|Whether attention persists outside the thread|Any official sequencing change between Zap and Work", "RELEASE → FAN HEAT → SHORT-FORM TEST → RESPONSE", "Do not claim the agency failed, ignored data, or chose the wrong title."],
"card_03": ["A fan-made K League starter guide is functioning as an unofficial front door for curious international supporters.", "A spike of attention can bring outsiders to a league faster than official explainers. Newcomers still need a simple route from curiosity to a club, rivalry, city, or match.", "The FMKorea receipt describes a K League entry-team guide circulating among foreign fans and the effort of translating it into Spanish. It is fan work, not league documentation.", "Starter packs reduce the first-click cost of fandom. They translate a complicated league into choices, becoming unpaid growth infrastructure.", "The humor is part of the interface, not evidence of formal intent. Fans built a decision aid because enthusiasm alone does not tell a newcomer where to begin.", "Whether clubs publish multilingual first-match guides|Whether fan translations circulate farther|Whether interest converts into viewing", "CURIOSITY → GUIDE → CLUB CHOICE → FIRST MATCH", "Do not present the joke guide as official policy or reproduce large portions."],
"card_04": ["Lingard attention quickly became a practical customer journey, and regular supporters answered questions hype alone cannot solve.", "A famous signing creates awareness in one headline. Attending requires tickets, seats, jerseys, transit, entry, and match-day expectations.", "The FMKorea source is a supporter guide responding to interest in K League and FC Seoul. It is peer context, not an official service notice; details should be confirmed officially.", "The gap between attention and attendance is infrastructure. Regular fans expose the conversion path and friction points clubs can clarify.", "Hype created questions; community knowledge made them actionable. The story is what happens after the headline.", "Whether multilingual guidance improves|Which practical questions repeat|Whether match-day interest persists", "HEADLINE → QUESTIONS → LOGISTICS → MATCH DAY", "Do not infer FC Seoul strategy or publish time-sensitive logistics as current."],}

CSS='''.read-meta{font-size:12px;color:var(--muted);font-weight:700}.editorial-depth section{padding:28px 0;margin:0;border-top:1px solid var(--line)}.editorial-depth h2{font:700 24px/1.2 Georgia,serif;text-transform:none;letter-spacing:0;margin:0 0 12px}.signal-sentence{border-left:4px solid var(--red);padding:18px 20px!important;background:#f7f7f6}.signal-sentence h2{font-size:11px;text-transform:uppercase;letter-spacing:.1em}.context-graphic{padding:38px 24px!important;background:#101828;color:#fff;border-top:8px solid #d93632!important}.context-graphic p{font:700 clamp(24px,5vw,42px)/1.2 Georgia,serif}.platform-context{background:#f5f6f7;padding:22px!important;border-top:3px solid var(--navy)!important}.watch-next li{font-size:16px;line-height:1.55;margin:8px 0}.claim-limit{font-size:13px!important;color:var(--muted);border-top:1px dashed var(--line);padding-top:14px}@media(max-width:760px){.editorial-depth section{padding:23px 0}.editorial-depth h2{font-size:21px}.signal-sentence,.platform-context{padding:17px!important}.watch-next li{font-size:15px}}'''

def apply_article_expansion(issue_dir):
    issue=Path(issue_dir)
    for cid,d in DATA.items():
        p=issue/'articles'/f'{cid}.html'; page=p.read_text(encoding='utf-8')
        if 'class="editorial-depth"' in page: continue
        lis=''.join(f'<li>{x}</li>' for x in d[5].split('|'))
        block=f'''<div class="editorial-depth"><section class="signal-sentence"><h2>The signal in one sentence</h2><p>{d[0]}</p></section><section><h2>Why this is showing up now</h2><p>{d[1]}</p></section><section class="platform-context"><h2>How to read the platform</h2><p>{d[2]}</p></section><section class="context-graphic" role="img" aria-label="{d[6]}"><p>{d[6]}</p></section><section><h2>Why it matters beyond the post</h2><p>{d[3]}</p></section><section><h2>A closer read</h2><p>{d[4]}</p><p class="claim-limit"><strong>Claim limit:</strong> {d[7]}</p></section><section class="watch-next"><h2>What to watch next</h2><ul>{lis}</ul></section></div>'''
        page=page.replace('<section><h2>Context & receipts</h2>',block+'<section><h2>Context & receipts</h2>',1).replace('</header><div class="article-body">','<p class="read-meta">3 min read · source-led editorial analysis</p></header><div class="article-body">',1).replace('</style>',CSS+'</style>',1)
        p.write_text(page,encoding='utf-8')
