import { chromium } from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import fs from 'node:fs';
const base='http://localhost:8080', routes=['/','/articles/card_01.html','/articles/card_02.html','/articles/card_03.html','/articles/card_04.html','/search.html','/about.html','/contact.html','/privacy.html','/accessibility.html','/terms.html'];
const viewports=[[1440,900],[1200,800],[768,1024],[390,844],[375,667],[320,568]], queries=['Billlie','빌리','Lingard','린가드','K League','K리그','팬덤','스포츠','뷰티','사회','푸드','美妆','美容','スポーツ','社会','<script>alert(1)</script>','   ','😀 "quotes" <angle>','x'.repeat(5001)];
const out={routes:{},viewports:[],search:[],interactions:{},axe:{}}; const browser=await chromium.launch({headless:true});
for(const route of routes){const context=await browser.newContext({viewport:{width:1200,height:800}}),page=await context.newPage(),problems=[];page.on('console',m=>{if(m.type()==='error')problems.push(`console: ${m.text()}`)});page.on('pageerror',e=>problems.push(`pageerror: ${e.message}`));const response=await page.goto(base+route,{waitUntil:'networkidle'});const broken=await page.locator('img').evaluateAll(ns=>ns.filter(i=>!i.complete||!i.naturalWidth).map(i=>i.getAttribute('src'))),duplicateIds=await page.locator('[id]').evaluateAll(ns=>{const c={};for(const n of ns)c[n.id]=(c[n.id]||0)+1;return Object.entries(c).filter(([,n])=>n>1)}),unsafeBlank=await page.locator('a[target="_blank"]').evaluateAll(as=>as.filter(a=>!a.relList.contains('noopener')||!a.relList.contains('noreferrer')).map(a=>a.href));out.routes[route]={status:response?.status(),broken,duplicateIds,unsafeBlank,problems};const axe=await new AxeBuilder({page}).analyze();out.axe[route]=axe.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.length}));await context.close()}
for(const [width,height] of viewports)for(const route of ['/','/articles/card_01.html']){const context=await browser.newContext({viewport:{width,height}}),page=await context.newPage();await page.goto(base+route,{waitUntil:'networkidle'});const m=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,bodyScrollWidth:document.body.scrollWidth}));out.viewports.push({width,height,route,...m,overflow:m.scrollWidth>m.clientWidth+1});await context.close()}
const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();await page.goto(base+'/',{waitUntil:'networkidle'});await page.locator('.search-toggle').click();const input=page.locator('.site-search input');for(const query of queries){await input.fill(query);await page.waitForTimeout(350);out.search.push({query:query.slice(0,80),length:query.length,hidden:await page.locator('.search-typeahead').getAttribute('hidden'),text:(await page.locator('.search-typeahead').innerText()).slice(0,300),scripts:await page.locator('.search-typeahead script').count()})}await input.press('Escape');out.interactions.escapeSearch={expanded:await page.locator('.search-toggle').getAttribute('aria-expanded'),value:await input.inputValue()};await page.locator('.lane-trigger').first().click();out.interactions.laneOpen=await page.locator('.lane-trigger').first().getAttribute('aria-expanded');await page.keyboard.press('Escape');out.interactions.laneEscape=await page.locator('.lane-trigger').first().getAttribute('aria-expanded');await page.goto(base+'/articles/card_01.html',{waitUntil:'networkidle'});const toggle=page.locator('.comment-toggle');await toggle.click();out.interactions.comment={expanded:await toggle.getAttribute('aria-expanded'),panelHidden:await page.locator('.comment-panel').getAttribute('hidden'),honeypotVisible:await page.locator('.honeypot').isVisible(),required:await page.locator('textarea[name="comment"]').getAttribute('required')!==null};await page.locator('textarea[name="comment"]').fill('<script>alert(1)</script> 한국어 日本語 中文 😀 https://example.test '+'x'.repeat(5000));out.interactions.commentScripts=await page.locator('.comment-panel script').count();out.interactions.discovery={related:await page.locator('.related-signal-card').count(),more:await page.locator('.issue-signal-card').count(),currentRelated:await page.locator('[data-related-card-id="card_01"]').count(),currentMore:await page.locator('[data-issue-card-id="card_01"]').count()};await context.close();await browser.close();fs.writeFileSync('outputs/issues/001/predeploy_browser_results.json',JSON.stringify(out,null,2));console.log(JSON.stringify({routes:Object.keys(out.routes).length,viewports:out.viewports.length,search:out.search.length,axeViolations:Object.values(out.axe).reduce((n,v)=>n+v.length,0)}));
